### ISSUE TITLE
微信小程序反编译反馈

### ISSUE THREAD

**Issue by shixiangkuangmo** [fasnow/fine#1]
1.能否增加小程序名称的显示
比如：
![image](https://github.com/fasnow/fine/assets/31498452/d0836e97-ea62-454e-9789-13d624fdc6c4)

2.微信小程序反编译不全
比如我用一个其它的老版本反编译程序，同时对某款小程序反编译后，可以搜到video_ad_currency这个请求：
![image](https://github.com/fasnow/fine/assets/31498452/de821e2d-fde9-4c56-b98c-a94b9421f16e)

但是您的程序反编译后：
![image](https://github.com/fasnow/fine/assets/31498452/255b7c90-2677-425b-8998-09a2b1ddc20b)
找不到对应的请求，求求大佬能不能修复下，已star

**Comment by fasnow** [comment]
方便说下哪个小程序吗

**Comment by shixiangkuangmo** [comment]
> 方便说下哪个小程序吗

第三个 猛犸充电

**Comment by shixiangkuangmo** [comment]
> 方便说下哪个小程序吗

#小程序://猛犸充电/bljauNQShKpSfhG

**Comment by fasnow** [comment]
> > 方便说下哪个小程序吗
> 
> #小程序://猛犸充电/bljauNQShKpSfhG

ok 后面我看看

**Comment by shixiangkuangmo** [comment]
> > > 方便说下哪个小程序吗
> > 
> > 
> > #小程序://猛犸充电/bljauNQShKpSfhG
> 
> ok 后面我看看

好的 感谢~

**Comment by shixiangkuangmo** [comment]
> > > 方便说下哪个小程序吗
> > 
> > 
> > #小程序://猛犸充电/bljauNQShKpSfhG
> 
> ok 后面我看看

老哥 修复没

**Comment by fasnow** [comment]
> > > > 方便说下哪个小程序吗
> > > 
> > > 
> > > #小程序://猛犸充电/bljauNQShKpSfhG
> > 
> > 
> > ok 后面我看看
> 
> 老哥 修复没

在换电脑配环境，就这两天修复，到时候程序内会有更新提示

**Comment by shixiangkuangmo** [comment]
> > > > > 方便说下哪个小程序吗
> > > > 
> > > > 
> > > > #小程序://猛犸充电/bljauNQShKpSfhG
> > > 
> > > 
> > > ok 后面我看看
> > 
> > 
> > 老哥 修复没
> 
> 在换电脑配环境，就这两天修复，到时候程序内会有更新提示

好的 爱你~

**Comment by fasnow** [comment]
> 1.能否增加小程序名称的显示 比如： ![image](https://private-user-images.githubusercontent.com/31498452/326685322-d0836e97-ea62-454e-9789-13d624fdc6c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzk1MzUsIm5iZiI6MTcxNTE3OTIzNSwicGF0aCI6Ii8zMTQ5ODQ1Mi8zMjY2ODUzMjItZDA4MzZlOTctZWE2Mi00NTRlLTk3ODktMTNkNjI0ZmRjNmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ODUyZjBiMTk0Mjg1NzIyNDUwNTZlMjM5YzcwNjY0YzVlZWE5MmQwZWY0OWU2NmZlN2M5Y2Y4OTAzOTVjYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SGgZ8p1GwKrPtvg6g9CfJIzkwLj-1g6wtqHIWuN8EiM)
> 
> 2.微信小程序反编译不全 比如我用一个其它的老版本反编译程序，同时对某款小程序反编译后，可以搜到video_ad_currency这个请求： ![image](https://private-user-images.githubusercontent.com/31498452/326685844-de821e2d-fde9-4c56-b98c-a94b9421f16e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzk1MzUsIm5iZiI6MTcxNTE3OTIzNSwicGF0aCI6Ii8zMTQ5ODQ1Mi8zMjY2ODU4NDQtZGU4MjFlMmQtZmRlOS00YzU2LWI5OGMtYTk0Yjk0MjFmMTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNGM0NWU5NjcyOTBiOWZmOGUzMDcyNjdiYzc2ZDNlOGFjZWIyZjI4N2Q0MjBlZGU0ZDQ2MTNlOWQ5YWY4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.guz9bTUtDvV9hO6z5Roh7fGSRFwPgmMT8qCO4QZap70)
> 
> 但是您的程序反编译后： ![image](https://private-user-images.githubusercontent.com/31498452/326685970-255b7c90-2677-425b-8998-09a2b1ddc20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzk1MzUsIm5iZiI6MTcxNTE3OTIzNSwicGF0aCI6Ii8zMTQ5ODQ1Mi8zMjY2ODU5NzAtMjU1YjdjOTAtMjY3Ny00MjViLTg5OTgtMDlhMmIxZGRjMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTFlOTA0MjQ2MjBkNTY2M2Q4NjMxZWFhMTE2ZTA2ZjdkYTQyMDg2OGE1MmUxYjNlOWQxYjE5MWRiNjNjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._-qIvAPI8D5MiNUyrtaO6iFiOO4YR9VymnUSWwAEfnA) 找不到对应的请求，求求大佬能不能修复下，已star

这个工具有链接吗

**Comment by shixiangkuangmo** [comment]
> > 1.能否增加小程序名称的显示 比如： ![image](https://private-user-images.githubusercontent.com/31498452/326685322-d0836e97-ea62-454e-9789-13d624fdc6c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzk1MzUsIm5iZiI6MTcxNTE3OTIzNSwicGF0aCI6Ii8zMTQ5ODQ1Mi8zMjY2ODUzMjItZDA4MzZlOTctZWE2Mi00NTRlLTk3ODktMTNkNjI0ZmRjNmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ODUyZjBiMTk0Mjg1NzIyNDUwNTZlMjM5YzcwNjY0YzVlZWE5MmQwZWY0OWU2NmZlN2M5Y2Y4OTAzOTVjYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SGgZ8p1GwKrPtvg6g9CfJIzkwLj-1g6wtqHIWuN8EiM)
> > 2.微信小程序反编译不全 比如我用一个其它的老版本反编译程序，同时对某款小程序反编译后，可以搜到video_ad_currency这个请求： ![image](https://private-user-images.githubusercontent.com/31498452/326685844-de821e2d-fde9-4c56-b98c-a94b9421f16e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzk1MzUsIm5iZiI6MTcxNTE3OTIzNSwicGF0aCI6Ii8zMTQ5ODQ1Mi8zMjY2ODU4NDQtZGU4MjFlMmQtZmRlOS00YzU2LWI5OGMtYTk0Yjk0MjFmMTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNGM0NWU5NjcyOTBiOWZmOGUzMDcyNjdiYzc2ZDNlOGFjZWIyZjI4N2Q0MjBlZGU0ZDQ2MTNlOWQ5YWY4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.guz9bTUtDvV9hO6z5Roh7fGSRFwPgmMT8qCO4QZap70)
> > 但是您的程序反编译后： ![image](https://private-user-images.githubusercontent.com/31498452/326685970-255b7c90-2677-425b-8998-09a2b1ddc20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzk1MzUsIm5iZiI6MTcxNTE3OTIzNSwicGF0aCI6Ii8zMTQ5ODQ1Mi8zMjY2ODU5NzAtMjU1YjdjOTAtMjY3Ny00MjViLTg5OTgtMDlhMmIxZGRjMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTFlOTA0MjQ2MjBkNTY2M2Q4NjMxZWFhMTE2ZTA2ZjdkYTQyMDg2OGE1MmUxYjNlOWQxYjE5MWRiNjNjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._-qIvAPI8D5MiNUyrtaO6iFiOO4YR9VymnUSWwAEfnA) 找不到对应的请求，求求大佬能不能修复下，已star
> 
> 这个工具有链接吗

 这个 https://github.com/wux1an/wxapkg

**Comment by shixiangkuangmo** [comment]
@fasnow 怎么样 有眉目吗

**Comment by fasnow** [comment]
> @fasnow 怎么样 有眉目吗

只优化了反编译问题，显示名称后续加

**Comment by shixiangkuangmo** [comment]
> > @fasnow 怎么样 有眉目吗
> 
> 只优化了反编译问题，显示名称后续加

好的 现在反编译后 代码全了吧

**Comment by shixiangkuangmo** [comment]
@fasnow 我试了一下 猛犸小程序 还是不全 搜不到
![image](https://github.com/fasnow/fine/assets/31498452/e4189c67-defb-46d7-b402-181b3820159e)
![image](https://github.com/fasnow/fine/assets/31498452/ac57d0f1-b5b4-4fa5-bd3a-1abf727826cb)

**Comment by shixiangkuangmo** [comment]
@fasnow fine支持分包吗？可能是这个导致的

**Comment by fasnow** [comment]
> @fasnow fine支持分包吗？可能是这个导致的

这个和你说那个用的工具不是同一个，存在些差异

**Comment by shixiangkuangmo** [comment]
> > @fasnow fine支持分包吗？可能是这个导致的
> 
> 这个和你说那个用的工具不是同一个，存在些差异

 嗯 就是小程序有的会有分包 打开页面才会加载 可能就会导致反编译不完整

**Comment by fasnow** [comment]
已改进，如果还是搜索不到那可能就是工具差异性
