### ISSUE TITLE
大佬您好

### ISSUE THREAD

**Issue by qzy0x** [fasnow/fine#11]
有交流群吗大佬

**Comment by fasnow** [comment]
> 有交流群吗大佬

暂时无哦，有什么问题可以直接issue哈

**Comment by FY036** [comment]
我很想知道你是怎么把ICP备案去掉验证的,真牛

**Comment by qzy0x** [comment]
搞一个呗师傅,;🥺🥺🥺

**Comment by fasnow** [comment]
该工具从来没有推广过，也不打算推广，所以交流群暂时没有这个打算，我也只是偶尔修修改改，代码什么都是全开源的，有什么疑问、意见以及建议可以在github提出我会及时处理哈。

**Comment by qzy0x** [comment]
牛逼ψ(｀∇´)ψ
