### ISSUE TITLE
小程序反编译无效

### ISSUE THREAD

**Issue by wintrysec** [fasnow/fine#4]
Windows平台上小程序反编译无任何反应。
检查发现本地目录不存在decompile.exe二进制文件

**Comment by fasnow** [comment]
日志是什么呢

**Comment by wintrysec** [comment]
fine/backend/service/service/wechat.(*Bridge).Decompile 159] [read decompile: is a directory]

点击反编译后的日志

**Comment by wintrysec** [comment]
【已解决】bin目录下的exe 可执行文件没有了，我自己改了代码替换成了https://github.com/wux1an/wxapkg这个项目的可执行文件，可以用了。
