### ISSUE TITLE
quake的问题

### ISSUE THREAD

**Issue by qzy0x** [fasnow/fine#7]
quake的导出每次都会少第一条的信息
quake的翻页只有第一页是对的,第二页对不上

**Comment by fasnow** [comment]
quake和00信安用的很少就没怎么更新这两个，目前主要fofa和hunter，其余两个有空更新

**Comment by qzy0x** [comment]
好的,quake域名收集的很全

**Comment by fasnow** [comment]
https://github.com/fasnow/fine/releases/tag/v1.1.11

**Comment by fasnow** [comment]
https://github.com/fasnow/fine/releases/tag/v1.1.11
